name: besso_log_book
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  auto_route: ^6.1.0
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.5
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  hooks_riverpod: ^2.3.4
  image_picker_web: ^3.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  simple_logger: ^1.9.0+2

dev_dependencies:
  auto_route_generator: ^6.1.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/